export const SITE_URL = "https://www.nishy.space";
export const SITE_NAME = "Nishanthan Janarthanarajah";

// Long-tail keywords derived from real experience (Eight25media/PandaDoc,
// Verdentra/Paycor/Snowflake, Concept Vines/Modjoul IoT, Rootcode Labs) to
// complement the raw skills list from Contentful for SEO + AEO.
export const EXTRA_KEYWORDS = [
  "Nishanthan Janarthanarajah",
  "Full Stack Developer",
  "Associate Technical Lead",
  "Technical Lead",
  "Software Engineer Sri Lanka",
  "Software Engineer Colombo",
  "Next.js Developer",
  "React Developer",
  "Node.js Developer",
  "NestJS Developer",
  "TypeScript Developer",
  "GraphQL Developer",
  "Contentful Developer",
  "Headless CMS Developer",
  "Vercel Developer",
  "AWS Cloud Engineer",
  "CI/CD Engineer",
  "SEO Engineer",
  "Technical SEO",
  "Web Performance Engineering",
  "Site Localization Pipeline",
  "IoT Platform Architecture",
  "Snowflake Data Migration",
  "Cross-functional Team Lead",
  "Agile Delivery Lead",
  "PandaDoc",
  "Eight25media",
  "Remote Software Engineer",
  "UI/UX Design",
  "Srilanka Software Engineer",
  "Colombo Software Engineer",
  "Freelance Full Stack Developer",
  "Jaffna Software Engineer",
  "Jaffna Full Stack Developer",
  "Jaffna Software Engineer for Hire",
  "Jaffna Full Stack Developer for Hire",
  "Jaffna Software Engineer for Freelance Projects",
  "Jaffna Full Stack Developer for Freelance Projects",
  "Jaffna Software Engineer for Contract Work",
  "Jaffna Full Stack Developer for Contract Work",
  "Jaffna Software Engineer for Remote Work",
  "Jaffna Full Stack Developer for Remote Work",
  "Jaffna Free lance Software Engineer",
  "Jaffna Free lance Full Stack Developer",
  "Jaffna Software Engineer for Hire",
  "Jaffna Full Stack Developer for Hire",
  "Jaffna Software Engineer for Freelance Projects",
  "Colombo Software Engineer for Freelance Projects",
  "Colombo Free lance Software Engineer",
  "Colombo Free lance Full Stack Developer",
  "Colombo Software Engineer for Contract Work",
  "Colombo Full Stack Developer for Contract Work",
  "Colombo Software Engineer for Remote Work",
  "Colombo Full Stack Developer for Remote Work",
];
