export const SITE_URL = "https://www.nishy.space";
export const SITE_NAME = "Nishanthan Janarthanarajah";

// Long-tail keywords derived from real experience (Eight25media/PandaDoc,
// Verdentra/Paycor/Snowflake, Concept Vines/Modjoul IoT, Rootcode Labs) to
// complement the raw skills list from Contentful for SEO + AEO.
export const EXTRA_KEYWORDS = [
  "Nishanthan Janarthanarajah",
  "Full Stack Developer",
  "Associate Technical Lead",
  "Technical Lead",
  "Software Engineer Sri Lanka",
  "Software Engineer Colombo",
  "Software Engineer Jaffna",
  "Freelance Full Stack Developer Sri Lanka",
  "Freelance Software Engineer Sri Lanka",
  "Hire a Full Stack Developer in Sri Lanka",
  "Next.js Developer",
  "React Developer",
  "Node.js Developer",
  "NestJS Developer",
  "TypeScript Developer",
  "GraphQL Developer",
  "Contentful Developer",
  "Headless CMS Developer",
  "Vercel Developer",
  "AWS Cloud Engineer",
  "CI/CD Engineer",
  "SEO Engineer",
  "Technical SEO",
  "Web Performance Engineering",
  "Site Localization Pipeline",
  "IoT Platform Architecture",
  "Snowflake Data Migration",
  "Cross-functional Team Lead",
  "Agile Delivery Lead",
  "PandaDoc",
  "Eight25media",
  "Remote Software Engineer",
  "UI/UX Design",
  "AI Engineer",
  "Generative AI Engineer",
  "LLM Application Engineering",
  "Retrieval-Augmented Generation",
  "RAG Developer",
  "Azure AI Foundry",
  "Azure OpenAI",
  "Pinecone Vector Database",
  "Model Context Protocol",
  "MCP Server Developer",
  "AI Agents",
  "Prompt Engineering",
  "Design-to-Code Automation",
  "Engineering Manager",
];
